# Generated by Django 5.0.2 on 2024-04-08 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_civil', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hijos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_hijos', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Medica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historial_medico', models.TextField(max_length=250, verbose_name='Historial médico')),
                ('sistematologia_actual', models.TextField(max_length=250, verbose_name='Sistematología actual')),
                ('medicamentos_actuales', models.TextField(max_length=250, verbose_name='Medicamentos actuales')),
                ('examenes_laboratorio', models.TextField(max_length=250, verbose_name='Exámenes de laboratorio')),
                ('examenes_imagenologia', models.TextField(max_length=250, verbose_name='Exámenes imagenología')),
                ('antecedentes_familiares', models.TextField(max_length=250, verbose_name='Antecedentes familiares')),
                ('antecedentes_personales', models.TextField(max_length=250, verbose_name='Antecedentes personales')),
                ('tension_arterial', models.FloatField(verbose_name='Tensión arterial')),
                ('glucemia', models.FloatField(verbose_name='Glucemia')),
                ('sat_O2', models.IntegerField(verbose_name='Saturación O2')),
            ],
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sangre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sangre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Basica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('lugar_nacimiento', models.CharField(max_length=100, verbose_name='Lugar de nacimiento')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('estatura', models.FloatField(verbose_name='Estatura')),
                ('peso', models.FloatField(verbose_name='Peso')),
                ('telefono', models.IntegerField(verbose_name='Teléfono')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('direccion_residencia', models.CharField(max_length=100, verbose_name='Dirección de residencia')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal_app.documento')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal_app.estado')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal_app.genero')),
                ('hijos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal_app.hijos')),
                ('ocupacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal_app.ocupacion')),
                ('sangre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portal_app.sangre')),
            ],
        ),
    ]
